# An example playbook where the share "exampleshare" will be created in the folder "/ftp/shares"
---

- hosts: all
  sudo: yes
  roles:
    - encron.vsftpd
  vars:
    vsftpd_shares_root: '/ftp/shares'
    vsftpd_shares:
      - name: exampleshare
        group: pirates
        directory_mode: u=rwx,g=rwx,o=rwx